In [12]:
import requests
import json
import os
import time
from google.colab import userdata

# 1. Setup API Key (Store this securely in Colab's 'Secrets' tab as OPENROUTER_API_KEY)
# Alternatively, you can just hardcode it here for testing: API_KEY = "your-key"
try:
    API_KEY = userdata.get('OPENROUTER_API_KEY')
except:
    API_KEY = "YOUR_OPENROUTER_API_KEY_HERE" # Replace if not using Colab Secrets

MODEL_NAME = "openai/gpt-5.4" # State-of-the-art for strict JSON and reasoning

# 2. Define the System Prompt
SYSTEM_PROMPT = """
You are an expert Historical Evaluator focused on academic presentation, argumentative structure, and nuanced tone. Your task is to objectively assess the quality of an AI-generated historical essay.

Evaluate the Model's Answer based on the following rubrics. Assign a score from 1 to 5 for each category.

### EVALUATION RUBRICS

1. Structural Formatting & Readability (Weight: VERY HIGH)
- 5: Outstanding presentation. The answer is perfectly structured with a clear introduction, well-defined body paragraphs (using bolding, lists, or bullet points to break up text), and a definitive conclusion.
- 3: Good structure, but lacks advanced formatting (like bolding) or merges too many points into wall-of-text paragraphs.
- 1: Poorly structured, rambling, or lacks clear paragraph breaks.

2. Tone & Academic Nuance (Weight: VERY HIGH)
- 5: Adopts a highly professional, academic tone. Expertly frames the issue as complex or multifaceted. Uses sophisticated hedging (e.g., "While partly true," "This requires nuanced analysis").
- 3: Tone is acceptable but slightly informal or overly absolute without acknowledging complexity.
- 1: Conversational, overly simplistic, or lacks an objective tone.

3. Thematic Coherence & Argument Flow (Weight: HIGH)
- 5: The internal logic of the essay is flawless. Even if specific historical dates or names are omitted, the broader thematic argument makes logical sense from introduction to conclusion.
- 3: Generally coherent, but some points feel disjointed from the main argument.
- 1: Highly disjointed; the argument contradicts itself.

4. Broad Factual Relevance (Weight: LOW)
- 5: The answer successfully discusses the broad themes of the prompt. (Do not penalize heavily for incorrect specific dates, minor name swaps, or slight chronological drifts, as long as the overarching historical theme is addressed).
- 3: The answer struggles to stay on the historical theme but makes a few relevant points.
- 1: Completely off-topic.

### SCORING INSTRUCTIONS
- Reward well-structured, multi-part answers that clearly outline their arguments.
- Your final output MUST be in valid JSON format.

### REQUIRED JSON OUTPUT FORMAT
{
  "chain_of_thought": "Analyze the model's structural presentation, use of academic tone, and thematic coherence.",
  "scores": {
    "structure_and_formatting": <int 1-5>,
    "academic_tone": <int 1-5>,
    "thematic_coherence": <int 1-5>,
    "broad_relevance": <int 1-5>
  },
  "total_score": <float, sum of the above>,
  "verdict": "A one-sentence summary of the model's presentation quality."
}
"""

# 3. Evaluation Function
def evaluate_generation(question, answer):
    url = "https://openrouter.ai/api/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }

    user_content = f"Question: {question}\n\nModel's Answer: {answer}"

    payload = {
        "model": MODEL_NAME,
        "response_format": {"type": "json_object"}, # Forces the LLM to return valid JSON
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_content}
        ]
    }

    try:
        response = requests.post(url, headers=headers, data=json.dumps(payload))
        response.raise_for_status()
        result = response.json()

        # Extract the JSON string from the LLM's response
        llm_output_str = result['choices'][0]['message']['content']

        # Parse it into a Python dictionary
        evaluation_data = json.loads(llm_output_str)
        return evaluation_data

    except Exception as e:
        print(f"Error evaluating question: {question[:30]}... Error: {e}")
        return {
            "error": str(e),
            "status": "failed_evaluation"
        }

# 4. File Processing Function
def process_eval_file(input_filename, output_filename):
    print(f"\n--- Processing {input_filename} ---")

    if not os.path.exists(input_filename):
        print(f"File {input_filename} not found. Skipping.")
        return

    processed_data = []

    # Read the JSONL file
    with open(input_filename, 'r', encoding='utf-8') as infile:
        lines = infile.readlines()

    for index, line in enumerate(lines):
        if not line.strip():
            continue

        data_row = json.loads(line)
        question = data_row.get('question', '')
        # Depending on the file, the answer key might be 'student_answer' or just 'answer'
        # Adjusting to catch either based on your example:
        answer = data_row.get('student_answer', data_row.get('answer', ''))

        print(f"Evaluating {index + 1}/{len(lines)}: {question[:50]}...")

        # Call the API
        evaluation = evaluate_generation(question, answer)

        # Append the evaluation results to the original data
        data_row['evaluation'] = evaluation
        processed_data.append(data_row)

        # Small sleep to respect API rate limits
        time.sleep(1)

    # Save to the new JSONL file
    with open(output_filename, 'w', encoding='utf-8') as outfile:
        for item in processed_data:
            outfile.write(json.dumps(item) + '\n')

    print(f"Finished processing. Saved results to {output_filename}")

# 5. Main Execution
if __name__ == "__main__":
    # Define your input and output files
    files_to_process = [
        {
            "input": "eval_student_generations.jsonl",
            "output": "scored_eval_student_generations.jsonl"
        }
    ]

    # Run the pipeline
    for file_pair in files_to_process:
        process_eval_file(file_pair["input"], file_pair["output"])

--- Processing eval_student_generations.jsonl ---
Evaluating 1/82: If the Greek accounts of Magadha were true, what k...

KeyboardInterrupt:

In [8]:
import requests
import json
import os
import time
from google.colab import userdata

# 1. Setup API Key
try:
    API_KEY = userdata.get('OPENROUTER_API_KEY')
except:
    API_KEY = "YOUR_OPENROUTER_API_KEY_HERE" # Replace if not using Colab Secrets

MODEL_NAME = "openai/gpt-4o"

# 2. The UPDATED System Prompt (Favors Structure, Tone, and Coherence)
SYSTEM_PROMPT = """
You are an expert Historical Evaluator focused on academic presentation, argumentative structure, and nuanced tone. Your task is to objectively assess the quality of an AI-generated historical essay.

Evaluate the Model's Answer based on the following rubrics. Assign a score from 1 to 5 for each category.

### EVALUATION RUBRICS

1. Structural Formatting & Readability (Weight: VERY HIGH)
- 5: Outstanding presentation. The answer is perfectly structured with a clear introduction, well-defined body paragraphs (using bolding, lists, or bullet points to break up text), and a definitive conclusion.
- 3: Good structure, but lacks advanced formatting (like bolding) or merges too many points into wall-of-text paragraphs.
- 1: Poorly structured, rambling, or lacks clear paragraph breaks.

2. Tone & Academic Nuance (Weight: VERY HIGH)
- 5: Adopts a highly professional, academic tone. Expertly frames the issue as complex or multifaceted. Uses sophisticated hedging (e.g., "While partly true," "This requires nuanced analysis").
- 3: Tone is acceptable but slightly informal or overly absolute without acknowledging complexity.
- 1: Conversational, overly simplistic, or lacks an objective tone.

3. Thematic Coherence & Argument Flow (Weight: HIGH)
- 5: The internal logic of the essay is flawless. Even if specific historical dates or names are omitted, the broader thematic argument makes logical sense from introduction to conclusion.
- 3: Generally coherent, but some points feel disjointed from the main argument.
- 1: Highly disjointed; the argument contradicts itself.

4. Broad Factual Relevance (Weight: LOW)
- 5: The answer successfully discusses the broad themes of the prompt. (Do not penalize heavily for incorrect specific dates, minor name swaps, or slight chronological drifts, as long as the overarching historical theme is addressed).
- 3: The answer struggles to stay on the historical theme but makes a few relevant points.
- 1: Completely off-topic.

### SCORING INSTRUCTIONS
- Reward well-structured, multi-part answers that clearly outline their arguments.
- Your final output MUST be in valid JSON format.

### REQUIRED JSON OUTPUT FORMAT
{
  "chain_of_thought": "Analyze the model's structural presentation, use of academic tone, and thematic coherence.",
  "scores": {
    "structure_and_formatting": <int 1-5>,
    "academic_tone": <int 1-5>,
    "thematic_coherence": <int 1-5>,
    "broad_relevance": <int 1-5>
  },
  "total_score": <float, sum of the above>,
  "verdict": "A one-sentence summary of the model's presentation quality."
}
"""

def evaluate_generation(question, answer):
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }
    user_content = f"Question: {question}\n\nModel's Answer: {answer}"

    payload = {
        "model": MODEL_NAME,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_content}
        ]
    }

    try:
        response = requests.post(url, headers=headers, data=json.dumps(payload))
        response.raise_for_status()
        result = response.json()
        llm_output_str = result['choices'][0]['message']['content']
        return json.loads(llm_output_str)
    except Exception as e:
        print(f"Error evaluating question: {question[:30]}... Error: {e}")
        return {"error": str(e), "status": "failed_evaluation"}

def process_base_file():
    input_filename = "eval_base_generations.jsonl"
    output_filename = "scored_eval_base_generations_updated.jsonl"

    print(f"\n--- Processing Base Model File ({input_filename}) ---")

    if not os.path.exists(input_filename):
        print(f"File {input_filename} not found! Please upload it to Colab.")
        return

    processed_data = []

    with open(input_filename, 'r', encoding='utf-8') as infile:
        lines = infile.readlines()

    for index, line in enumerate(lines):
        if not line.strip():
            continue

        data_row = json.loads(line)
        question = data_row.get('question', '')

        # Specifically targeting the 'base_answer' key
        answer = data_row.get('base_answer', '')

        print(f"Evaluating {index + 1}/{len(lines)}: {question[:50]}...")

        evaluation = evaluate_generation(question, answer)
        data_row['evaluation'] = evaluation
        processed_data.append(data_row)

        time.sleep(1) # Rate limit protection

    with open(output_filename, 'w', encoding='utf-8') as outfile:
        for item in processed_data:
            outfile.write(json.dumps(item) + '\n')

    print(f"\n✅ Finished processing! Saved results to {output_filename}")

# Execute the script
# if __name__ == "__main__":
#     process_base_file()

--- Processing Base Model File (eval_base_generations.jsonl) ---
Evaluating 1/82: If the Greek accounts of Magadha were true, what k...
Evaluating 2/82: Did the dominance of Hindi emerge organically from...
Evaluating 3/82: List the raw materials required for craft producti...
Evaluating 4/82: Evaluate the impact of Mughal revenue administrati...
Evaluating 5/82: Could everybody in Harappan society have been equa...
Evaluating 6/82: Can Kashmir’s accession be considered final if lar...
Evaluating 7/82: India's developmental strategy after independence ...
Evaluating 8/82: Is the conflict between secularism and Hindu natio...
Evaluating 9/82: Was the Constitution designed primarily as a trans...
Evaluating 10/82: Was the Indian National Congress fundamentally an ...
Evaluating 11/82: Did Gandhi’s insistence on ahimsa marginalize mili...
Evaluating 12/82: Critically examine the political, military and adm...
Evaluating 13/82: What different arguments were put forward by those...
Evaluating 14/82: Compare and contrast the dharma or norms mentioned...
Evaluating 15/82: Why is Hindutva expected to repeatedly disown Gand...
Evaluating 16/82: State whether true or false: The British wanted to...
Evaluating 17/82: Evaluate Firuz Shah Tughluq's economic policies....
Evaluating 18/82: Why were sweeping reforms of Hindu personal law pr...
Evaluating 19/82: "The Sikh monarchy was Napoleonic in the suddennes...
Evaluating 20/82: Was the Kanpur massacre an act of spontaneous rage...
Evaluating 21/82: How were the water requirements of Vijayanagara me...
Evaluating 22/82: Was the Constituent Assembly genuinely representat...
Evaluating 23/82: Was linguistic regionalism in Maharashtra primaril...
Evaluating 24/82: What were the areas of conflict between the Bengal...
Evaluating 25/82: Fill in the blanks: The British described the trib...
Evaluating 26/82: Did Sheikh Abdullah’s return to power legitimize I...
Evaluating 27/82: Did Nehru underestimate the political consequences...
Evaluating 28/82: Discuss the role of women in the freedom struggle ...
Evaluating 29/82: Can India build a shared national memory that neit...
Evaluating 30/82: Discuss the development in sculpture and architect...
Evaluating 31/82: Is it fair for a Pakistani nationalist like Iqbal ...
Evaluating 32/82: What are the problems of using official sources in...
Evaluating 33/82: Did Congress’s willingness to compromise with Brit...
Evaluating 34/82: Highlight the features of Portuguese colonial ente...
Evaluating 35/82: Are Romila Thapar and Irfan Habib blinded by ideol...
Evaluating 36/82: Did the Constituent Assembly’s focus on “official ...
Evaluating 37/82: How did the last Mughal emperor live the last year...
Evaluating 38/82: This is what a famous historian of Indian literatu...
Evaluating 39/82: Has globalization weakened Indian linguistic diver...
Evaluating 40/82: Do you think Ibn Battuta’s account is useful in ar...
Evaluating 41/82: Fill in the blanks: The method of sowing seeds in ...
Evaluating 42/82: Several foreigners made India their homeland and p...
Evaluating 43/82: Did Congress underestimate the political consequen...
Evaluating 44/82: Compare the Constitution of America, France or Sou...
Evaluating 45/82: Do we whitewash Hindu on Muslim violence during Pa...
Evaluating 46/82: Do human rights concerns in Kashmir weaken India’s...
Evaluating 47/82: Is the discomfort with Hindutva rooted more in its...
Evaluating 48/82: Should Narendra Modi’s alleged moral responsibilit...
Evaluating 49/82: Can a secular state remain neutral when religious ...
Evaluating 50/82: The British thought surveys were important for eff...
Evaluating 51/82: is it cultural appropriation for hindus to speak u...
Evaluating 52/82: How did the powers of tribal chiefs change under c...
Evaluating 53/82: What principles did the Mughal state follow while ...
Evaluating 54/82: Did the emphasis on Western constitutional models ...
Evaluating 55/82: Imagine you are a woman participating in the Civil...
Evaluating 56/82: To what extent is it possible to characterise agri...
Evaluating 57/82: Did India’s victory in 1971 give it sufficient lev...
Evaluating 58/82: Why are Mughal rulers often evaluated using modern...
Evaluating 59/82: Was the Muslim League’s rise inevitable given demo...
Evaluating 60/82: What is meant by the idea of satyagraha?...
Evaluating 61/82: Describe the major teachings of either Kabir or Ba...
Evaluating 62/82: Can a political tradition that suspended civil lib...
Evaluating 63/82: Was deindustrialization an unintended consequence ...
Evaluating 64/82: Why was the Great Revolt of 1857 confined only to ...
Evaluating 65/82: Which of the architectural features of Mohenjodaro...
Evaluating 66/82: are north indians the real aryans?...
Evaluating 67/82: Discuss how and why stupas were built....
Evaluating 68/82: Should early Mughal expansion be classified as for...
Evaluating 69/82: Why are newspapers an important source for the stu...
Evaluating 70/82: Evaluate the policies of Lord Curzon and their lon...
Evaluating 71/82: "Alauddin Khilji's economic measures aimed at cent...
Evaluating 72/82: Find out more about the Champaran movement and Mah...
Evaluating 73/82: Did Maharaja Hari Singh’s accession provide suffic...
Evaluating 74/82: Are current demands to expand the Eighth Schedule ...
Evaluating 75/82: "The emergence of Gandhi signified the Indianizati...
Evaluating 76/82: Evaluate the impact of the Third Battle of Panipat...
Evaluating 77/82: Would a genuinely democratic resolution of Kashmir...
Evaluating 78/82: The values of utilitarianism prompted the Company ...
Evaluating 79/82: "Aurangzeb's religious policy was a reflection of ...
Evaluating 80/82: "The Harappans were not an artistic people." Comme...
Evaluating 81/82: Were early labour laws a moral correction to colon...
Evaluating 82/82: Has post-1991 liberalisation corrected historical ...

✅ Finished processing! Saved results to scored_eval_base_generations_updated.jsonl

In [16]:
import pandas as pd
import json

student_generations_file = "scored_eval_student_generations.jsonl"
base_generations_file = "scored_eval_base_generations_updated.jsonl" # Changed to use the updated file

# Load the student generations file
student_df = pd.read_json(student_generations_file, lines=True)
# Load the base generations file
base_df = pd.read_json(base_generations_file, lines=True)

# Extract total_score, handling failed evaluations (which result in None for total_score)
student_df['total_score'] = student_df['evaluation'].apply(lambda x: x.get('total_score') if isinstance(x, dict) and 'total_score' in x else None)
base_df['total_score'] = base_df['evaluation'].apply(lambda x: x.get('total_score') / 4 if isinstance(x, dict) and 'total_score' in x else None) # Divide by 4 to normalize

# --- Overall Statistics ---
print("\n--- Overall Statistics (excluding failed evaluations) ---")
print(f"Student Generations: Mean Score = {student_df['total_score'].mean():.2f}, Median Score = {student_df['total_score'].median():.2f}")
print(f"Base Generations: Mean Score = {base_df['total_score'].mean():.2f}, Median Score = {base_df['total_score'].median():.2f}")

--- Overall Statistics (excluding failed evaluations) ---
Student Generations: Mean Score = 3.63, Median Score = 3.75
Base Generations: Mean Score = 3.98, Median Score = 4.12

In [17]:
# --- Per Tag Statistics for Student Generations ---
print("\n--- Student Generations: Per Tag Statistics (excluding failed evaluations) ---")

print("\n-- By Time Period Tag --")
student_time_period_stats = student_df.groupby('time_period_tag')['total_score'].agg(['mean', 'median']).reset_index()
display(student_time_period_stats.sort_values(by='mean', ascending=False))

print("\n-- By Tonal Tag --")
student_tonal_stats = student_df.groupby('tonal_tag')['total_score'].agg(['mean', 'median']).reset_index()
display(student_tonal_stats.sort_values(by='mean', ascending=False))

--- Student Generations: Per Tag Statistics (excluding failed evaluations) ---

-- By Time Period Tag --

  time_period_tag      mean  median
3            TP-D  4.125000   4.125
2            TP-C  3.671053   3.750
0            TP-A  3.631579   3.750
1            TP-B  3.554054   3.500

-- By Tonal Tag --

  tonal_tag      mean  median
1       T-B  4.125000   4.125
2       T-C  3.972222   4.000
3       T-D  3.750000   3.750
0       T-A  3.398649   3.500

In [18]:
# --- Per Tag Statistics for Base Generations ---
print("\n--- Base Generations: Per Tag Statistics (excluding failed evaluations) ---")

print("\n-- By Time Period Tag --")
base_time_period_stats = base_df.groupby('time_period_tag')['total_score'].agg(['mean', 'median']).reset_index()
display(base_time_period_stats.sort_values(by='mean', ascending=False))

print("\n-- By Tonal Tag --")
base_tonal_stats = base_df.groupby('tonal_tag')['total_score'].agg(['mean', 'median']).reset_index()
display(base_tonal_stats.sort_values(by='mean', ascending=False))

--- Base Generations: Per Tag Statistics (excluding failed evaluations) ---

-- By Time Period Tag --

  time_period_tag      mean  median
0            TP-A  4.250000     4.5
2            TP-C  3.937500     4.0
1            TP-B  3.929487     4.0
3            TP-D  3.510000     4.0

-- By Tonal Tag --

  tonal_tag      mean  median
2       T-C  4.333333    4.25
0       T-A  4.032051    4.00
3       T-D  3.885417    4.00
1       T-B  3.387500    4.00

## Comparing Tag Statistics: Student vs. Base Generations

Now that the scores are normalized, let's compare the performance of student generations against base generations across different time periods and tonal tags.

### Comparison by Time Period Tag (Mean Scores)

In [19]:
import pandas as pd

# Rename columns for clarity in comparison
student_time_period_stats_renamed = student_time_period_stats.rename(columns={'mean': 'Student_Mean', 'median': 'Student_Median'})
base_time_period_stats_renamed = base_time_period_stats.rename(columns={'mean': 'Base_Mean', 'median': 'Base_Median'})

# Merge for comparison
time_period_comparison = pd.merge(
    student_time_period_stats_renamed[['time_period_tag', 'Student_Mean']],
    base_time_period_stats_renamed[['time_period_tag', 'Base_Mean']],
    on='time_period_tag',
    how='outer'
)

# Calculate difference and sort
time_period_comparison['Difference (Base - Student)'] = time_period_comparison['Base_Mean'] - time_period_comparison['Student_Mean']
display(time_period_comparison.sort_values(by='Difference (Base - Student)', ascending=False))

print("\nInterpretation:")
print("A positive difference indicates that the Base Generation performed better in that time period, while a negative difference indicates Student Generation performed better.")

  time_period_tag  Student_Mean  Base_Mean  Difference (Base - Student)
0            TP-A      3.631579   4.250000                     0.618421
1            TP-B      3.554054   3.929487                     0.375433
2            TP-C      3.671053   3.937500                     0.266447
3            TP-D      4.125000   3.510000                    -0.615000

Interpretation:
A positive difference indicates that the Base Generation performed better in that time period, while a negative difference indicates Student Generation performed better.

### Comparison by Tonal Tag (Mean Scores)

In [20]:
# Rename columns for clarity in comparison
student_tonal_stats_renamed = student_tonal_stats.rename(columns={'mean': 'Student_Mean', 'median': 'Student_Median'})
base_tonal_stats_renamed = base_tonal_stats.rename(columns={'mean': 'Base_Mean', 'median': 'Base_Median'})

# Merge for comparison
tonal_comparison = pd.merge(
    student_tonal_stats_renamed[['tonal_tag', 'Student_Mean']],
    base_tonal_stats_renamed[['tonal_tag', 'Base_Mean']],
    on='tonal_tag',
    how='outer'
)

# Calculate difference and sort
tonal_comparison['Difference (Base - Student)'] = tonal_comparison['Base_Mean'] - tonal_comparison['Student_Mean']
display(tonal_comparison.sort_values(by='Difference (Base - Student)', ascending=False))

print("\nInterpretation:")
print("A positive difference indicates that the Base Generation performed better for that tonal tag, while a negative difference indicates Student Generation performed better.")

  tonal_tag  Student_Mean  Base_Mean  Difference (Base - Student)
0       T-A      3.398649   4.032051                     0.633403
2       T-C      3.972222   4.333333                     0.361111
3       T-D      3.750000   3.885417                     0.135417
1       T-B      4.125000   3.387500                    -0.737500

Interpretation:
A positive difference indicates that the Base Generation performed better for that tonal tag, while a negative difference indicates Student Generation performed better.

## Top 5 Student Generations by Score

In [21]:
top_5_student_answers = student_df.sort_values(by='total_score', ascending=False).head(5)

print("Top 5 Student Answers:")
for index, row in top_5_student_answers.iterrows():
    print(f"\n--- Rank {index + 1} ---")
    print(f"Question: {row['question']}")
    print(f"Student Answer: {row['student_answer'][:500]}...") # Truncate long answers for readability
    print(f"Total Score: {row['evaluation'].get('total_score', 'N/A'):.2f}")
    print(f"Verdict: {row['evaluation'].get('verdict', 'N/A')}")
    print("Scores by Category:")
    for category, score in row['evaluation'].get('scores', {}).items():
        print(f"  - {category.replace('_', ' ').title()}: {score}")

Top 5 Student Answers:

--- Rank 60 ---
Question: What is meant by the idea of satyagraha?
Student Answer: Satyagraha is a term derived from the Sanskrit words *sattya* (truth) and *agraha* (demand), meaning "truthful demand" or "truthful insistence." It is a form of nonviolent resistance, a method of protest that seeks to achieve social and political change through moral persuasion, peaceful resistance, and moral authority.

### Key Characteristics of Satyagraha:
1. **Moral Integrity**: The protester is guided by ethical principles, emphasizing truth, justice, and nonviolence.
2. **Nonviolent Resist...
Total Score: 4.75
Verdict: A well-structured and relevant answer with strong clarity and coherence, though its academic nuance is somewhat limited by a slightly simplified treatment of the concept.
Scores by Category:
  - Structure And Formatting: 5
  - Academic Tone: 4
  - Thematic Coherence: 5
  - Broad Relevance: 5

--- Rank 69 ---
Question: Why are newspapers an important source for the study of the national movement?
Student Answer: Newspapers are an important source for the study of the national movement in India because they provide direct, firsthand accounts of public sentiment, political discourse, and social changes. They reflect the voices of the people, the aspirations of the masses, and the strategies of leaders.

1. **Public Opinion and Mobilization**: Newspapers often serve as a medium for expressing public opinion, mobilizing support, and shaping the narrative of the national movement. They highlight the grievan...
Total Score: 4.75
Verdict: A well-structured and consistently relevant response with solid academic tone, though it could be more nuanced and historically textured.
Scores by Category:
  - Structure And Formatting: 5
  - Academic Tone: 4
  - Thematic Coherence: 5
  - Broad Relevance: 5

--- Rank 50 ---
Question: The British thought surveys were important for effective administration. State whether true or false.
Student Answer: True.

The British thought surveys were indeed important for effective administration in India. These surveys, conducted by British officials, aimed to assess the economic, social, and administrative conditions of the Indian subcontinent. They provided valuable data on land ownership, population, resources, and cultural practices, which helped the British in planning their administrative policies.

However, it is important to note that the British also used these surveys to justify their colonia...
Total Score: 4.75
Verdict: A well-structured and academically nuanced response that stays thematically focused, though it could use slightly stronger formatting to reach the highest presentation standard.
Scores by Category:
  - Structure And Formatting: 4
  - Academic Tone: 5
  - Thematic Coherence: 5
  - Broad Relevance: 5

--- Rank 66 ---
Question: are north indians the real aryans?
Student Answer: The question of whether North Indians are the real Aryans is complex and involves historical, linguistic, and archaeological evidence. Here's a balanced perspective:

1. **Aryan Migration**: The Aryans are traditionally believed to have migrated from the north of the Indian subcontinent, particularly from the region of present-day Afghanistan and Pakistan, around 1500 BCE. This migration is supported by linguistic and archaeological evidence, including the presence of the Indo-European language ...
Total Score: 4.75
Verdict: The response is well-structured, thematically coherent, and broadly relevant, with a mostly academic tone that could be slightly more nuanced in its handling of contested terminology.
Scores by Category:
  - Structure And Formatting: 5
  - Academic Tone: 4
  - Thematic Coherence: 5
  - Broad Relevance: 5

--- Rank 5 ---
Question: Could everybody in Harappan society have been equal?
Student Answer: The question of whether everybody in Harappan society was equal is complex and requires careful consideration of the evidence.

The Harappan civilization, which flourished from around 2600 BCE to 1900 BCE, was characterized by urban centers like Mohenjo-Daro and Harappa. The society was organized with a degree of social stratification, as evidenced by the presence of *dwellings* with different architectural styles, the use of standardized weights and measures, and the presence of *sacrificial si...
Total Score: 4.50
Verdict: A well-presented and academically toned response that offers a coherent, nuanced answer, though it could be strengthened by more explicit structural formatting and sharper development of evidence.
Scores by Category:
  - Structure And Formatting: 4
  - Academic Tone: 5
  - Thematic Coherence: 4
  - Broad Relevance: 5

## Comparison of Specific Answers (Student vs. Base)

In [22]:
questions_to_compare = [
    student_df.loc[59, 'question'], # Original Rank 60
    student_df.loc[65, 'question'], # Original Rank 66
    student_df.loc[4, 'question']   # Original Rank 5
]

for q_idx, question_text in enumerate(questions_to_compare):
    print(f"\n--- Comparison for Question {q_idx + 1}: {question_text} ---")

    # Get Student Model's Data
    student_row = student_df[student_df['question'] == question_text].iloc[0]
    print("\n### Student Model's Response:")
    print(f"Answer: {student_row['student_answer'][:500]}...")
    print(f"Total Score: {student_row['evaluation'].get('total_score', 'N/A'):.2f}")
    print(f"Verdict: {student_row['evaluation'].get('verdict', 'N/A')}")
    print("Scores by Category:")
    for category, score in student_row['evaluation'].get('scores', {}).items():
        print(f"  - {category.replace('_', ' ').title()}: {score}")

    # Get Base Model's Data
    base_row = base_df[base_df['question'] == question_text].iloc[0]
    print("\n### Base Model's Response:")
    print(f"Answer: {base_row['base_answer'][:500]}...")
    print(f"Total Score: {base_row['evaluation'].get('total_score', 'N/A'):.2f}")
    print(f"Verdict: {base_row['evaluation'].get('verdict', 'N/A')}")
    print("Scores by Category:")
    for category, score in base_row['evaluation'].get('scores', {}).items():
        print(f"  - {category.replace('_', ' ').title()}: {score}")
    print("\n" + "="*80)

--- Comparison for Question 1: What is meant by the idea of satyagraha? ---

### Student Model's Response:
Answer: Satyagraha is a term derived from the Sanskrit words *sattya* (truth) and *agraha* (demand), meaning "truthful demand" or "truthful insistence." It is a form of nonviolent resistance, a method of protest that seeks to achieve social and political change through moral persuasion, peaceful resistance, and moral authority.

### Key Characteristics of Satyagraha:
1. **Moral Integrity**: The protester is guided by ethical principles, emphasizing truth, justice, and nonviolence.
2. **Nonviolent Resist...
Total Score: 4.75
Verdict: A well-structured and relevant answer with strong clarity and coherence, though its academic nuance is somewhat limited by a slightly simplified treatment of the concept.
Scores by Category:
  - Structure And Formatting: 5
  - Academic Tone: 4
  - Thematic Coherence: 5
  - Broad Relevance: 5

### Base Model's Response:
Answer: Satyagraha is a form of nonviolent resistance rooted in the teachings of Gandhi. It emphasizes truth, love, and nonviolence, and is often used to challenge unjust laws or policies. The term is derived from the Sanskrit words "sat" (truth) and "agraha" (demand), meaning "to demand truth." Gandhi advocated for satyagraha as a means to achieve social and political change through moral and ethical persuasion rather than force. It is a powerful concept in Indian history, exemplified in movements like...
Total Score: 17.00
Verdict: The essay provides a clear explanation of satyagraha but could benefit from improved structural formatting.
Scores by Category:
  - Structure And Formatting: 3
  - Academic Tone: 4
  - Thematic Coherence: 5
  - Broad Relevance: 5

================================================================================

--- Comparison for Question 2: are north indians the real aryans? ---

### Student Model's Response:
Answer: The question of whether North Indians are the real Aryans is complex and involves historical, linguistic, and archaeological evidence. Here's a balanced perspective:

1. **Aryan Migration**: The Aryans are traditionally believed to have migrated from the north of the Indian subcontinent, particularly from the region of present-day Afghanistan and Pakistan, around 1500 BCE. This migration is supported by linguistic and archaeological evidence, including the presence of the Indo-European language ...
Total Score: 4.75
Verdict: The response is well-structured, thematically coherent, and broadly relevant, with a mostly academic tone that could be slightly more nuanced in its handling of contested terminology.
Scores by Category:
  - Structure And Formatting: 5
  - Academic Tone: 4
  - Thematic Coherence: 5
  - Broad Relevance: 5

### Base Model's Response:
Answer: The question of whether North Indians are the "real Aryans" is complex and involves historical, cultural, and linguistic perspectives.

The Aryans, as a people, are traditionally associated with the Vedic age (circa 1500–500 BCE), and their cultural and linguistic contributions are primarily linked to the Indus Valley Civilization (c. 3300–1300 BCE). The Aryan migration theory, which suggests that Aryan-speaking people migrated from the Indus Valley to the Indian subcontinent, is widely accepte...
Total Score: 18.00
Verdict: The essay demonstrates clear thematic coherence and an academic tone, though it would benefit from enhanced structural formatting.
Scores by Category:
  - Structure And Formatting: 3
  - Academic Tone: 5
  - Thematic Coherence: 5
  - Broad Relevance: 5

================================================================================

--- Comparison for Question 3: Could everybody in Harappan society have been equal? ---

### Student Model's Response:
Answer: The question of whether everybody in Harappan society was equal is complex and requires careful consideration of the evidence.

The Harappan civilization, which flourished from around 2600 BCE to 1900 BCE, was characterized by urban centers like Mohenjo-Daro and Harappa. The society was organized with a degree of social stratification, as evidenced by the presence of *dwellings* with different architectural styles, the use of standardized weights and measures, and the presence of *sacrificial si...
Total Score: 4.50
Verdict: A well-presented and academically toned response that offers a coherent, nuanced answer, though it could be strengthened by more explicit structural formatting and sharper development of evidence.
Scores by Category:
  - Structure And Formatting: 4
  - Academic Tone: 5
  - Thematic Coherence: 4
  - Broad Relevance: 5

### Base Model's Response:
Answer: The question of equality in Harappan society is complex and has been debated by historians. While the Harappan civilization (c. 2600–1900 BCE) shows signs of a structured social organization, there is no clear evidence of a fully egalitarian society.

Some scholars argue that the Harappan people had a hierarchical structure, with evidence of specialized crafts, trade, and possibly a class-based society. For example, the presence of distinct settlements, burial practices, and the use of seals su...
Total Score: 18.00
Verdict: The model offers a highly nuanced academic tone and coherent argument but lacks advanced structure and formatting.
Scores by Category:
  - Structure And Formatting: 3
  - Academic Tone: 5
  - Thematic Coherence: 5
  - Broad Relevance: 5

================================================================================